### ISSUE TITLE
Reproducibility Report of "Variational Sparse Coding"

### ISSUE THREAD

**Issue by reproducibility-org** [ReScience/submissions#1]
**Original article:** Variational Sparse Coding (https://openreview.net/forum?id=SkeJ6iR9Km)

**PDF URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/FrazadaTigre-SkeJ6iR9Km/ReScience_submission.pdf
**Metadata URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/FrazadaTigre-SkeJ6iR9Km/metadata-draft.yaml
**Code URL:** https://zenodo.org/record/2657330#.XMzD46YpBSM

**Scientific domain:** Machine Learning
**Programming language:** Python
**Suggested editor:** ICLR Reproducibility Challenge Editors

**Corresponding Author:** @Alfo5123
**Challenge PR:**  https://github.com/reproducibility-challenge/iclr_2019/pull/146

[ICLR Reproducibility Challenge, 2019](https://github.com/reproducibility-challenge/iclr_2019/)

**Comment by reproducibility-org** [comment]
Reviewer Comments:

1. https://github.com/reproducibility-challenge/iclr_2019/pull/146#issuecomment-465430111
2. https://github.com/reproducibility-challenge/iclr_2019/pull/146#issuecomment-466789449
3. https://github.com/reproducibility-challenge/iclr_2019/pull/146#issuecomment-467059942

**Comment by rougier** [comment]
@Alfo5123 Can you use the latest rescience template to make sure to use the proper font. Also, you'll need to edit the metadata (editorial -> replication), reviewer is "anoynmous", volume is 5, issue is 2.

**Comment by rougier** [comment]
Also, the title of the replication must  be "[Re] original title" (this will helps people searching for the original article to find yours as well)

**Comment by koustuvsinha** [comment]
@rougier updated draft as per comments.

**Comment by rougier** [comment]
LGTM. I'm waiting for the 3 others and I'll upload them to Zenodo.

**Comment by koustuvsinha** [comment]
updated, also sent you the raw latex source

**Comment by rougier** [comment]
Can you check everything is ok: https://www.dropbox.com/s/fyzdo4jbfu57ppj/article-2.pdf?dl=0

**Comment by rougier** [comment]
You can access it at: https://github.com/rougier/ICLR-2019/tree/master/article-2

**Comment by koustuvsinha** [comment]
Looks good to me!
