### ISSUE TITLE
[Rp] Structural flexibility in proteins: impact of the crystal environment

### ISSUE THREAD

**Issue by khinsen** [ReScience/submissions#14]
**Original article:** [Hinsen, K (2008) Structural flexibility in proteins: impact of the crystal environment. Bioinformatics 24:521.](https://doi.org/10.1093/bioinformatics/btm625) ([Open Access version](https://academic.oup.com/bioinformatics/article-pdf/24/4/521/16884353/btm625.pdf))

**PDF URL:**  https://github.com/khinsen/rescience-ten-year-challenge-paper-3/raw/master/article/article.pdf
**Metadata URL:**  https://github.com/khinsen/rescience-ten-year-challenge-paper-3/raw/master/article/metadata.yaml
**Code URL:**  https://github.com/khinsen/rescience-ten-year-challenge-paper-3/

**Scientific domain:**  Biophysics
**Programming language:**  Python
**Suggested editor:**  @delsuc

**Comment by rougier** [comment]
@delsuc Can you edit this submission to the "Ten year reproducibility challenge" ?

**Comment by delsuc** [comment]
ok, no problem.

**Comment by rougier** [comment]
Thanks. Note that you need only one reviewer (because this is a reproduction)

**Comment by delsuc** [comment]
@pdebuyl could you review this submission ?

**Comment by pdebuyl** [comment]
Hi @delsuc 

I reviewed the first submission. I think that it would be best to get another reviewer to proof the process for the ten year challenge. I am ok to review anyway after next week if necessary.

**Comment by delsuc** [comment]
@fxcoudert would you be able to handle this review ?

**Comment by fxcoudert** [comment]
@delsuc Here is my review

## Paper

I quite appreciated the non-nonsense writing of the paper, which is good for a reproducibility study to show the pitfalls and issues, even when they turn out not to be crucial. 

- Regarding the numpy evolutions, which I think are quite important to the community at large, maybe this could be better characterised: what is the numpy policy on breaking changes, deprecation process, and use of semantic versioning? Maybe links to this information could be added. (But that opens another 10-year challenge: if a paper has web links, how many will still be active 10 years later?)
- The instructions for reproduction are rather clear, and the recommendation to use Guix is interesting (I know of it, and want to try it myself but haven't found the time yet).
- The main point I think could be discussed is the use of Python 2, given the EOL was earlier this year (2020-01-01), and it is being removed from software distributions. How long does the author suggest it will be feasible to install Python 2 on modern hardware? Or without a dedicated OS like Guix? I would be interested in comments on that, as I think it's a worrying topic.
- Grace is still working fine, I am using it daily :)
- I do not understand why there are two folders named `updated-scripts-from-obsolete-web-server` and `scripts-from-suplementary-material-to-original-paper`, and they are not documented in the paper. One of them has an extra script (`calculate_crystal_fluctuations_small_memory.py`) which is not mentioned anywhere else either. _Edit: I see that the notes file mentions those. Probably best to mention that in the paper itself, though._

## Typo

- “there is longer any point in such a change” (page 1)

**Comment by delsuc** [comment]
Thank you very much @fxcoudert !
@khinsen can you improve the document as mentionned ?

**Comment by khinsen** [comment]
Thanks @fxcoudert for a very helpful review and thanks @delsuc for finding such a helpful reviewer!

I will submit a revision taking into account all the suggestions in about ten days.

**Comment by khinsen** [comment]
@delsuc @fxcoudert The revision is ready!

BIg change: I have added a section at the end of the Conclusions that discusses the evolution of Python 2 and NumPy in the context of computational science.

Small changes: all the other remarks in the review.

In preparation for the ten-year link rot challenge, I only refer to archived copies from the [Internet Archive](https://archive.org/index.php). Let's hope it will stay around for ten more years at least!

**Comment by rougier** [comment]
Gentle reminder

**Comment by delsuc** [comment]
I believe this is ready for acceptation and publication.
@fxcoudert is that ok with you ?

**Comment by fxcoudert** [comment]
✅ Looks good to me!

**Comment by khinsen** [comment]
Thanks @fxcoudert ! I suspect @delsuc will pronounce acceptance, but I am waiting for this to happen because I have to put the official date of acceptance into the final version of the article.

**Comment by delsuc** [comment]
Sorry @khinsen for the delay - the period is a bit complex to deal with... :-/
Of course the manuscript is accepted to be published is ReScience.
I am not sure what is the procedure at this level...

**Comment by khinsen** [comment]
Thanks @delsuc !

The procedure for actually publishing the article is described [here](https://github.com/rescience/articles). Roughly, the steps are
- assigning an article number
- reserving a DOI on Zenodo
- produce a new PDF with the DOI (that's a job for me)
- publish the PDF on Zenodo
- add the article to the ReScience table of contents.

Since this is purely technical, with no decisions involved, I can actually do all of this myself if you prefer. I see no potential conflict of interest. But if you want to practice the job which allows certain commercial publishers to make lots of money, go ahead and ask @rougier or myself for help if you get stuck (the current procedure is still rather new).

**Comment by delsuc** [comment]
I'll try to do that - probably this W.E.

**Comment by rougier** [comment]
Gentle reminder.

**Comment by khinsen** [comment]
@delsuc Gentle reminder... including my offer to do this myself if you don't have time.

**Comment by delsuc** [comment]
Sorry about this - go ahead - I thought I would find time, but it's getting worse.
(I really wanted to learn)

**Comment by khinsen** [comment]
I am sure there will be further occasions, in quieter times!

**Comment by khinsen** [comment]
This article has been published (http://doi.org/10.5281/zenodo.3886447) and will soon be listed on the ReScience Web site.

**Comment by rougier** [comment]
It's online.
