### ISSUE TITLE
Reproducibility Report of "Meta learning with differentiable closed-form solvers"

### ISSUE THREAD

**Issue by reproducibility-org** [ReScience/submissions#2]
**Original article:** : Meta-learning with differentiable closed-form solvers (https://openreview.net/pdf?id=HyxnZh0ct7)

**PDF URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/LCAX-HyxnZh0ct7/LCAX_camera_ready.pdf
**Metadata URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/LCAX-HyxnZh0ct7/ReScience_src/metadata-draft.yaml
**Code URL:** https://zenodo.org/record/2662494#.XMzE-aYpBSM

**Scientific domain:** Machine Learning
**Programming language:** Python
**Suggested editor:** ICLR Reproducibility Challenge Editors

**Corresponding Author:**  @ArnoutDevos
**Challenge PR:** https://github.com/reproducibility-challenge/iclr_2019/pull/150

[ICLR Reproducibility Challenge, 2019](https://github.com/reproducibility-challenge/iclr_2019)

**Comment by reproducibility-org** [comment]
Reviewer comments:

1. https://github.com/reproducibility-challenge/iclr_2019/pull/150#issuecomment-464272161
2. https://github.com/reproducibility-challenge/iclr_2019/pull/150#issuecomment-464889846
3. https://github.com/reproducibility-challenge/iclr_2019/pull/150#issuecomment-475799455

**Comment by rougier** [comment]
@ArnoutDevos Can you use the latest rescience template to make sure to use the proper font. Also, you'll need to edit the metadata, reviewer is "anonymous", volume is 5, issue is 2.

**Comment by rougier** [comment]
Also, the title of the replication must  be "[Re] original title" (this will helps people searching for the original article to find yours as well)

**Comment by koustuvsinha** [comment]
@rougier updated the draft with the recommended changes.

**Comment by rougier** [comment]
Thanks. Page 8 is mostly empty, do you know why (some extra \clearpage ?)

**Comment by koustuvsinha** [comment]
updated, also sent you the raw latex source

**Comment by rougier** [comment]
I'm now editing the paper. I would need a DOI for the code, would it be possible for the authors to deposit their code on Zenodo and give me the corresponding DOI?

**Comment by ArnoutDevos** [comment]
Available: 10.5281/zenodo.2662494
[https://zenodo.org/record/2662494#.XORbLdMzZ24](https://zenodo.org/record/2662494#.XORbLdMzZ24)

**Comment by rougier** [comment]
By the way, you confirm the two last authors have no ORCID?

**Comment by ArnoutDevos** [comment]
Sylvain Chatel does: [0000-0002-1275-8367](https://orcid.org/0000-0002-1275-8367)

**Comment by rougier** [comment]
Can you chech everything is ok:  https://www.dropbox.com/s/ohi1n1qsyovixsg/article-1.pdf?dl=0

**Comment by ArnoutDevos** [comment]
Thank you for editing our work.

   1. if possible, put small spacing between paragraphs to improve
   readability (unless there's a strict policy on this).
   2. Sylvain Chatel's ORCID is not yet next to his name
   3. If possible, shift content end of page 1 to 2, end of 4 to 5
   4. page 6 looks very empty

That's all I guess.

Thanks,
Arnout

**Comment by rougier** [comment]
Thanks for your comments. At this point, maybe the easiest for me would be to upload the edited version such that you can tweak it.

**Comment by rougier** [comment]
You can access it at: https://github.com/rougier/ICLR-2019/tree/master/article-1

**Comment by koustuvsinha** [comment]
Looks good to me!

**Comment by rougier** [comment]
@ArnoutDevos can you take care of your suggested changes?

**Comment by ArnoutDevos** [comment]
@rougier will do by next week. Have a deadline this week.

**Comment by rougier** [comment]
I'll do it then (I want to have them published today).

**Comment by ArnoutDevos** [comment]
Ok, thanks :)!

**Comment by rougier** [comment]
@ArnoutDevos I've update the PDF. Can you have a look?

**Comment by ArnoutDevos** [comment]
Looks good to me!
