### ISSUE TITLE
Reproducibility Report of "h-detach: Modifying the LSTM gradient towards better optimization"

### ISSUE THREAD

**Issue by reproducibility-org** [ReScience/submissions#3]
**Original article:**  h-detach: Modifying the LSTM Gradient Towards Better Optimization (https://openreview.net/pdf?id=ryf7ioRqFX)

**PDF URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/TeamYakataka-ryf7ioRqFX/TeamYakataka_camera_ready.pdf
**Metadata URL:** 
**Code URL:** https://zenodo.org/record/2657361#.XMq6eEPhXCI

**Scientific domain:** Machine Learning
**Programming language:** Python
**Suggested editor:** ICLR Reproducibility Challenge Editors

**Corresponding Author:** @dido1998
**Challenge PR:** https://github.com/reproducibility-challenge/iclr_2019/pull/148

[ICLR Reproducibility Challenge, 2019](https://github.com/reproducibility-challenge/iclr_2019/)

**Comment by reproducibility-org** [comment]
Reviewer comments:

1. https://github.com/reproducibility-challenge/iclr_2019/pull/148#issuecomment-467280259
2. https://github.com/reproducibility-challenge/iclr_2019/pull/148#issuecomment-467295329
3. https://github.com/reproducibility-challenge/iclr_2019/pull/148#issuecomment-474682125

**Comment by rougier** [comment]
@dido1998 Can you use the latest rescience template to make sure to use the proper fonts? Also, you'll need to edit the metadata (editorial -> replication), reviewer is "anonymous", volume is 5, issue is 2. Also, make sure URL display properly at the bottom of first page.

**Comment by rougier** [comment]
And metadata file is missing.

**Comment by rougier** [comment]
Also, the title of the replication must  be "[Re] original title" (this will helps people searching for the original article to find yours as well)

**Comment by koustuvsinha** [comment]
Updated metadata file: https://github.com/dido1998/iclr-reproducibility-template/blob/master/metadata-draft.yaml

**Comment by koustuvsinha** [comment]
@rougier updated the pdf file. The metadata can be found here: https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/TeamYakataka-ryf7ioRqFX/metadata.yaml

**Comment by rougier** [comment]
Thanks. Missing email  for corresponding author. The "replication of ..." is weird. In the end, maybe it woudl be easier if can edit the latex myself. Do you have sources for all of them ?

**Comment by koustuvsinha** [comment]
updated, also sent you the raw latex source

**Comment by rougier** [comment]
Can you check everything is ok: https://www.dropbox.com/s/ywevie7iy3l6rsg/article-4.pdf?dl=0

**Comment by rougier** [comment]
You can access it at: https://github.com/rougier/ICLR-2019/tree/master/article-4

**Comment by koustuvsinha** [comment]
Looks good to me!
