### ISSUE TITLE
10 year challenge: Eglen and Wong (2008)

### ISSUE THREAD

**Issue by sje30** [ReScience/submissions#34]
**Original article:** https://arxiv.org/abs/1208.0986 (postprint of 2008 paper)

**PDF URL:**  https://github.com/sje30/rescience-hor/blob/master/template-master/article2.pdf
**Metadata URL:**  https://github.com/sje30/rescience-hor/blob/master/template-master/metadata.yaml
**Code URL:**  https://github.com/sje30/rescience-hor/

**Scientific domain:**  Computational Neuroscience
**Programming language:**  R
**Suggested editor:**  Timothée Poisot or Karthik Ram or Etienne Roesch

**Comment by sje30** [comment]
Apologies in advance for grafting your pdf onto the front of my pdf -- I ran out of time to investigate if your article style could be used with Rmarkdown.  So creating article2.pdf was my solution.

**Comment by rougier** [comment]
Thanks for your submission, we'll assign an editor soon. For the published version (if accepted), that would be great if you can use the template.

I'll edit your submission.

**Comment by rougier** [comment]
@thmosqueiro Can you review this submission for the Ten Years Reproducibility Challenge ?

**Comment by sje30** [comment]
> Thanks for your submission, we'll assign an editor soon. For the
> published version (if accepted), that would be great if you can use
> the template.

yes, of course, will be able to swtich to your template.  I think I can
just export the markdown to .tex and then fix up from there.

**Comment by rougier** [comment]
@rgutzen @junpenglao @rcaze @iampritishpatil Can you review thus submission for the Ten Years Reproducibility Challenge ?

**Comment by rgutzen** [comment]
Sorry, I'm afraid I have no experience with R.

**Comment by rougier** [comment]
@rguten Thanks for your answer. @junpenglao @rcaze @iampritishpatil @benoit-girard @rossant ca you reviwe this (short) paper?

**Comment by iampritishpatil** [comment]
Sorry I missed the tag last time. I don't think I'd manage well as I haven't used R in several years, and seems there are a non trivial amount of code and dependencies in R. I'm sorry.

**Comment by rougier** [comment]
@iampritishpatil No problem, thank for the answer.

**Comment by rcaze** [comment]
Sorry for not answering earlier, I just started to re-enabled notification on github. I'm afraid my knowledge of R is also insufficient.

**Comment by benoit-girard** [comment]
I haven't used R in the last 17 years, I fear I won't be able to examine the code...

**Comment by rougier** [comment]
@thmosqueiro @ChrisRackauckas Could you review this submission (https://github.com/ReScience/submissions/issues/34) ?

**Comment by ChrisRackauckas** [comment]
I am afraid I do not have the bandwidth right now to properly handle this! Sorry!

**Comment by rougier** [comment]
@ChrisRackauckas @benoit-girard Thanks for the answer.
@eroesch stephanmg degoldschmidt Could you review this article (R + Computational Neuroscience) ?

**Comment by rougier** [comment]
Sorry for the delay. @eroesch @stephanmg @degoldschmidt Could you review this article (R + Computational Neuroscience) ?

**Comment by rougier** [comment]
Oh my god, I'm very late on following this submission.  @ChrisRackauckas @thmosqueiro @eroesch @stephanmg @degoldschmidt Could you review this article (R + Computational Neuroscience) ?

**Comment by stephanmg** [comment]
Hi @rougier I could review it.

**Comment by sje30** [comment]
Thank you both!  I had forgotten about this.  I just checked the repo, and it looks like the binder broke sometime in the last year (rmarkdown needs to be installed, and there is a small pandoc-citeproc issue).  Can you give me the weekend to fix this, which in the interim will update it to R version 4.0 and handle the change in pandoc-citeproc which is now missing from Ubuntu (this will teach me not to pin all the versions down for mybinder!)

**Comment by sje30** [comment]
The `launch binder` button on the readme of https://github.com/sje30/rescience-hor is working again; just needed a couple of tweaks to system R images that had changed in the last year.

**Comment by stephanmg** [comment]
Hi,

since this is my first review, can somebody give me some pointers for best practices on how the review should be conducted?

**Comment by rougier** [comment]
Sure, have a look at: https://rescience.github.io/edit/

Note that this submission is related to the "Ten Years Reproducibility Challenge" where authors try to reproduce (re-run) their own code. You can also browse [open reviews](https://github.com/ReScience/submissions/issues?q=is%3Aissue+label%3A%22Ten+Years+Challenge%22+is%3Aclosed) on the same issue.

**Comment by stephanmg** [comment]
@sje30 I looked at your reproduction. 

I have some suggestions for (minor) revision before accepting the submission:
Figures:
- Figure 1: Original figure is black/white, I would avoid using red/green colors for the dots - will be much easier to discriminate for people with color vision deficiency.

Code:
-  `Error: Status code 504 returned` - I assume this some Binder-related issue?
- `hor_bdmin.R` - contains some commented code which seems not necessary, can this be removed?
- `maps2.R`  - same as above
- Overall many empty lines and superfluous white space, could you correct this?

Altogether great replication of figures and tables.  This looks good!

**Review criteria:**
1. Reproducibility of the replication: Yes, I can reproduce via Binder and on my computer.
2. Clarity and completeness of the accompanying article: Great, everything ran OOTB for me.
3. Clarity of the code: Okay.
4. Clarity and completeness of the accompanying article: Okay.

**Comment by sje30** [comment]
Thanks for doing this so promptly!

> - Figure 1: Original figure is black/white, I would avoid using
> red/green colors for the dots - will be much easier to discriminate
> for people with color vision deficiency.

The 'red' is actually 'orangered' for the exact reason you mention.  I
can change it to blue though if you prefer?

> Code:
> -  `Error: Status code 504 returned` - I assume this some
> Binder-related issue?

Hmm... the binder just worked for me now.  Could you please try again?


> - `hor_bdmin.R` - contains some commented code which seems not
> necessary, can this be removed?

> - `maps2.R`  - same as above
I can certainly tidy it up!  great idea.


> - Overall many empty lines and superfluous whitespace, could you
> correct this?

Is that in the R files?


> Altogether great replication of figures and tables. This looks okay.


Thank you.

**Comment by stephanmg** [comment]
> Thanks for doing this so promptly!
> - Figure 1: Original figure is black/white, I would avoid using red/green colors for the dots - will be much easier to discriminate for people with color vision deficiency.
> The 'red' is actually 'orangered' for the exact reason you mention. I can change it to blue though if you prefer?

Well, call me pedantic, I would just prefer black and white as in the original figure.
> Code: - `Error: Status code 504 returned` - I assume this some Binder-related issue?
> Hmm... the binder just worked for me now. Could you please try again?

Will try again later.

> - `hor_bdmin.R` - contains some commented code which seems not necessary, can this be removed? - `maps2.R` - same as above
> I can certainly tidy it up! great idea.
> - Overall many empty lines and superfluous whitespace, could you correct this?
> Is that in the R files?
Yes, in the R files, there is a lot of empty lines, sometimes in sequence.
> Altogether great replication of figures and tables. This looks okay.
> Thank you.

Besides this, I would suggest to tidy up the repository into code and markup if possible.

**Comment by stephanmg** [comment]
By the way: I am a little confused about the following: You write that the arXiv paper is a post print, do you mean preprint? Because I see your paper being published in `Vis Neurosci.`  (and I would call this a post print) and arXiv is obviously a preprint server.

**Comment by rougier** [comment]
@sje30 Can you address the comments?

**Comment by sje30** [comment]
Thanks for these.  Bit behind, but yes, I hope to do these in the next few days... thanks for the comments.

**Comment by sje30** [comment]
hi all, am now working through these.

Postprint == correct here, I think.  I uploaded the article to arxiv long after the paper was accepted.

**Comment by sje30** [comment]
I have reverted figure 1 to b/w, and removed excess comments.

I'm now getting problems however getting article.tex to compile.  I think it may be my lack of python skills, but when I run make in the template_master folder, I get the following error:

```
make         
./yaml-to-latex.py -i metadata.yaml -o metadata.tex
Traceback (most recent call last):
  File "/home/stephen/proj/2020/rescience-hor/template-master/./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "/home/stephen/proj/2020/rescience-hor/template-master/./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
make: *** [Makefile:18: metadata.tex] Error 1
```

I did also have to fix article.py to specify which loader to use.

**Comment by sje30** [comment]
```
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> print (yaml.__version__)
5.4.1
```

**Comment by rougier** [comment]
Can you check if you have the latest version of the article template (with `yaml-to-latex.py`)?

**Comment by sje30** [comment]
thanks.  I started over with a fresh template/ and that seemed to do the job nicely.  I have now pushed the new version to github, and converted from the Rmarkdown to use the template.  See: https://github.com/sje30/rescience-hor/blob/master/template/article.pdf

**Comment by sje30** [comment]
Do I need to do anything on here to signal the paper is ready for checking again?

**Comment by rougier** [comment]
sorry for the delay. Articlel looks good to me and from the review by @stephanmg I think we can accept the paper.

I'll try to edit it today starting from your new version. Stay tuned.

**Comment by rougier** [comment]
I would need a software heritage ID. Can you save your repo at https://www.softwareheritage.org/save-and-reference-research-software/ and give me back the corresponding swid?

**Comment by sje30** [comment]
Thanks @rougier but am having problems uploading to software heritage.  https://twitter.com/StephenEglen/status/1428808288506945536?s=20

perhaps it is just Friday night and it will be better in the morning!

**Comment by khinsen** [comment]
Software heritage seems to have some technical issues at the moment, I didn't manage to save a GitHub repo yesterday. BTW, you don't need an account there, what you did should have been sufficient.

**Comment by sje30** [comment]
Thanks Konrad.  Seems to be a bit healthier this morning -- I can see this now:

https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/sje30/rescience-hor

**Comment by sje30** [comment]
@rougier : is this what you need?
swh:1:dir:6088b7312865b39a4a5f5af78556bf6da5fa6409;origin=https://github.com/sje30/rescience-hor;visit=swh:1:snp:a2df6c1cf91ec9a80d08026d7728a503eb64c7a6;anchor=swh:1:rev:0882985f8a0e3ea32f8898175460bacc8060b552

**Comment by sje30** [comment]
[![SWH](https://archive.softwareheritage.org/badge/swh:1:dir:6088b7312865b39a4a5f5af78556bf6da5fa6409/)](https://archive.softwareheritage.org/swh:1:dir:6088b7312865b39a4a5f5af78556bf6da5fa6409;origin=https://github.com/sje30/rescience-hor;visit=swh:1:snp:a2df6c1cf91ec9a80d08026d7728a503eb64c7a6;anchor=swh:1:rev:0882985f8a0e3ea32f8898175460bacc8060b552)

**Comment by rougier** [comment]
Yes, sorry for the delay. I'll try to do it today!

**Comment by rougier** [comment]
The sandboxed version is online at https://sandbox.zenodo.org/record/908095, can you check if everything's ok? Then I'll proceed with the actual publication.

**Comment by sje30** [comment]
Super, thanks @rougier -- all looks good to me.

**Comment by rougier** [comment]
It's online at https://zenodo.org/record/5347786 ! Congratulations. It should appear soon on rescience website (a few minutes)

**Comment by sje30** [comment]
Thanks!  Great job.

**Comment by rougier** [comment]
And so sorry for the very long delay until publication.

**Comment by sje30** [comment]
no problem at all!
