### ISSUE TITLE
[Re] [Ten Year Challenge] Oscillating chemical reactions and phase separation simulated by molecular dynamics

### ISSUE THREAD

**Issue by kneth** [ReScience/submissions#36]
**Original article:** https://aip.scitation.org/doi/abs/10.1063/1.475237
```
@article{Geisshirt:1997,
  author  = {Kenneth Geisshirt and Eigil L. Praestgaard and Soren Toxvaerd},
  title   = {Oscillating chemical reactions and phase separation simulated by molecular dynamics},
  journal = {Journal of Chemical Physics},
  volume  = {107},
  number  = {22},
  pages   = {9406--9412},
  year    = {1997}
}
```

**PDF URL:**  https://github.com/kneth/rescience-ten-year-challenge-paper/blob/master/article.pdf 
**Metadata URL:**  https://github.com/kneth/rescience-ten-year-challenge-paper/blob/master/metadata.yaml
**Code URL:**  https://github.com/kneth/MDreac/tree/master/oldsrc

**Scientific domain:**  non-equilibrium thermodynamics, chemical kinetics
**Programming language:**  Fortran-77
**Suggested editor:**

**Comment by kneth** [comment]
Declaration of participation: https://github.com/ReScience/ten-years/issues/1#issuecomment-549156688

**Comment by rougier** [comment]
Thanks for your submission, we'll assign an editor soon.

@khinsen Can you find an editor (or edit yourself) for this submission?

**Comment by pdebuyl** [comment]
Hi @rougier I can edit.

**Comment by rougier** [comment]
Thanks @pdebuyl.

**Comment by pdebuyl** [comment]
Just a notice to let you know that "reviewer finding" is well in process.

**Comment by pdebuyl** [comment]
@fhoefling , can you review this submission ?

**Comment by fhoefling** [comment]
I started with the review. Some first feedback on the software:

A detailed guide of how to proceed is missing and should be given. Yet, building the programme went smoothly, just by installing `gfortran` and running `make` in `oldsrc`.

Next, I started the script `phd.sh` from the `protocols` folder. On a Xeon E3-1241 @ 3.50GHz, the script was running for more than 5 hours on a single core and created almost 8 GB of data. Is this the intended behaviour? If so they user should be alerted. No further output was created.

I've got the following Python error repeatedly:

> File "../../../diffcoeff.py", line 8, in \<module\>
      from sklearn.linear_model import LinearRegression
      ModuleNotFoundError: No module named 'sklearn'

Please use the linear regression functionality from a more basic library. Machine learning approaches were not needed in the original work.

The provided README is rather brief. It mentions some means to run the programme in parallel. Is this still possible today?

**Comment by pdebuyl** [comment]
@kneth even though the review is still ongoing, you may already take into account the first comments of @fhoefling

**Comment by fhoefling** [comment]
Actually, I can only continue with the reviewing after the aforementioned  
issues have been solved. Currently, the programme does not output data. I  
apologise that I have not communicated this more clearly.

**Comment by pdebuyl** [comment]
thanks @fhoefling for the feedback.
@kneth can you address the current feedback so that we can proceed?

**Comment by kneth** [comment]
@pdebuyl Yes, I will address it in the couple of days. 

@fhoefling Thanks for taking the time to review.

**Comment by pdebuyl** [comment]
@kneth could you address the comments?

**Comment by kneth** [comment]
@pdebuyl Sorry - forgot all about it. I will try to get it done during the weekend.

**Comment by kneth** [comment]
@pdebuyl 

Sorry for not getting things done earlier. I have created https://github.com/kneth/MDreac/pull/4 to address the first comments. I hope to rerun the analysis steps once more to see if I get the same result as before.

**Comment by pdebuyl** [comment]
Hi @kneth ,

Any update?

**Comment by kneth** [comment]
@pdebuyl As I haven't had any progress for months, I think it is best to withdraw my submission. Please accept my apology for the time you have wasted.

**Comment by rougier** [comment]
If you think you can work on this submision in the next few months, we can leave it opened and send you gentle reminders regularly. We've no real time pressure.

**Comment by kneth** [comment]
@rougier If I go back to work on the submission in the next few month, I will reopen.
