### ISSUE TITLE
Reproducibility Report of "Learning Neural PDE Solvers with Convergence Guarantees"

### ISSUE THREAD

**Issue by reproducibility-org** [ReScience/submissions#4]
**Original article:** Learning Neural PDE Solvers with Convergence Guarantees (https://openreview.net/forum?id=rklaWn0qK7)

**PDF URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/zoidberg-rklaWn0qK7/zoidberg_camera_ready.pdf
**Metadata URL:** https://github.com/reproducibility-challenge/iclr_2019/blob/master/papers/zoidberg-rklaWn0qK7/rescience_report/metadata-draft.yaml
**Code URL:** https://zenodo.org/record/2660730

**Scientific domain:** Machine Learning
**Programming language:** Python
**Suggested editor:** ICLR Reproducibility Challenge Editors

**Corresponding Author:** @francescobardi
**Challenge PR:** https://github.com/reproducibility-challenge/iclr_2019/pull/136

[ICLR Reproducibility Challenge, 2019](https://github.com/reproducibility-challenge/iclr_2019)

**Comment by reproducibility-org** [comment]
Reviewer comments:

1. https://github.com/reproducibility-challenge/iclr_2019/pull/136#issuecomment-464268146
2. https://github.com/reproducibility-challenge/iclr_2019/pull/136#issuecomment-466598313
3. https://github.com/reproducibility-challenge/iclr_2019/pull/136#issuecomment-473885655

**Comment by rougier** [comment]
@francescobardi Can you use the latest rescience template to make sure to use the proper font. Also, you'll need to edit the metadata (editorial -> replication), reviewer is "anonymous", volume is 5, issue is 2. Also, make sure URL displya properly in the bottom of first page.

**Comment by rougier** [comment]
Also, the title of the replication must  be "[Re] original title" (this will helps people searching for the original article to find yours as well)

**Comment by koustuvsinha** [comment]
@rougier fixed the issues (metadata, volume and url display)

**Comment by rougier** [comment]
Thanks. For the title, maybe you can replace the type by "ICLR Reproducibility Challenge 2019" (instead of replication) and remove it from the title. For the editor, we need some name, can you put your name ?

**Comment by koustuvsinha** [comment]
updated, also sent you the raw latex source

**Comment by rougier** [comment]
I'm editing the article and I would need the code DOI (if not available can you ask the authors to deposit an archive on Zenodo and to communicate the DOI?)

**Comment by rougier** [comment]
Can you check eveyrhting is ok (but the code DOI): https://www.dropbox.com/s/a64uscxmv7n2dav/article-3.pdf?dl=0

**Comment by rougier** [comment]
You can access it at: https://github.com/rougier/ICLR-2019/tree/master/article-3

**Comment by koustuvsinha** [comment]
Looks good to me!

**Comment by rougier** [comment]
@koustuvsinha For this one the code DOI is still missing.

**Comment by koustuvsinha** [comment]
Hi @rougier , the code DOI for this project is https://zenodo.org/record/2660730
