### ISSUE TITLE
Ten Years Reproducibility Challenge: Drivers of Evapotranspiration from Boreal Wildfires

### ISSUE THREAD

**Issue by bpbond** [ReScience/submissions#40]
**Original article:** https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2486.2008.01776.x

**PDF URL:** https://github.com/bpbond/ten-years-paper33/blob/master/article/paper33-report.pdf
**Metadata URL:** https://github.com/bpbond/ten-years-paper33/blob/master/article/metadata.yaml
**Code URL:** https://github.com/bpbond/ten-years-paper33

**Scientific domain:** Earth Sciences/Ecology
**Programming language:** R
**Suggested editor:**

**Comment by rougier** [comment]
Thanks for your submission. We'll assign an editor soon.

@tpoisot @karthik Could you edit this submission for the Ten Years Reproducibility Challenge (only 1 reviewer neeed) ?

**Comment by karthik** [comment]
Yes. Sorry for the delay (it's been challenging this past month).

**Comment by rougier** [comment]
@karthik Thank you. Given the situation, we can have reasonable delay in the review. Note that only one reviewer is needed.

**Comment by rougier** [comment]
@karthik Gentle reminder

**Comment by karthik** [comment]
_Waiting on a couple of responses this week_

**Comment by karthik** [comment]
@bpbond Hi Ben. I'm having trouble finding reviewers. Are you able to suggest anyone independent who might be able to evaluate your work?

**Comment by bpbond** [comment]
Hi @karthik . Thanks for taking this on. Some suggestions:
* Xiao Feng, fengxiao@e-mail.arizona.edu  
* [Martin De Kauwe](http://mdekauwe.github.io/), mdekauwe@gmail.com  
* Michael White, m.white@us.nature.com
* Jackie Mathes,  jmatthes@wellesley.edu
* David LeBauer, dlebauer@email.arizona.edu
* Jennifer Holm, jaholm@lbl.gov

**Comment by karthik** [comment]
@jhmatthes will review. 🙏

**Comment by jhmatthes** [comment]
I successfully reproduced the results in the author's code. I have just one small suggestion to the paper: it would be helpful to specify which "fit statistics" were reported in the paper that were reproduced in this particular analysis.

**Comment by karthik** [comment]
Thanks @jhmatthes Much appreciated.

**Comment by jhmatthes** [comment]
And to add, I found the accompanying article clear and complete, and the article is sufficiently self-contained.

**Comment by karthik** [comment]
Sorry for the delay @bpbond but I'll proceed with accepting your paper now. Stay tuned for next steps.

**Comment by rougier** [comment]
Great, @karthik ping me if you need some help with the publication process.

**Comment by bpbond** [comment]
Thanks, all.

**Comment by bpbond** [comment]
Hi @karthik , all, any update here? Thanks.

**Comment by rougier** [comment]
@karthik Tell me if you need help with the publication process.

**Comment by rougier** [comment]
@bpbond Sorry for the long delay, I'll handle the publication. Can you convert your article to the ReScience template?

**Comment by karthik** [comment]
Thanks @rougier I couldn't make the submission tool work unfortunately.

**Comment by rougier** [comment]
@karthik No problem.
@bpbond Do you need some help converting your submission to the ReScience template ?

**Comment by bpbond** [comment]
Sorry @rougier — I will take a look at this in the next day or two and get back to you.

**Comment by rougier** [comment]
@bpbond Any progress?

**Comment by bpbond** [comment]
My sincere apologies—a busy last month but I am back and determined to finish this!

@rougier I did this article in R Markdown, but am not a LaTeX user and wondering what you suggest for converting to the ReScience template. Looking at the [template repository](https://github.com/ReScience/template), from what I understand one option is to install all the needed LaTeX tools locally, clone the repo, and use that. A second would be Overleaf (entering `metadata.tex` manually). Any recommendation?

Thanks.

**Comment by bpbond** [comment]
OK, I have moved the article content into a new Overleaf project, based on the ReScience template: https://www.overleaf.com/read/...

Attaching the resulting PDF here:
[Bond_Lamberty_ReScience.pdf](https://github.com/ReScience/submissions/files/6136685/Bond_Lamberty_ReScience.pdf)

@rougier Does this look good? What's my next step? Thanks for your help.

**Comment by rougier** [comment]
Look goods to me! I'll make a local copy of your overleaf and edit it to add publication infromation. In the meantime, can you save your code at software heritage (https://www.softwareheritage.org/save-and-reference-research-software/). The process is straightforward). You should obtain as swid that is needed for publication.

**NOTE:** I edited your post above to remove the overleaf link (else, anybody can modify your files)

**Comment by bpbond** [comment]
OK, it's up on Software Heritage: https://archive.softwareheritage.org/browse/revision/b8fe7506c23641ff7bc43deed4573feaa6d03947/?origin_url=https://github.com/bpbond/ten-years-paper33.git&timestamp=2021-03-15T15:55:00Z

I think this means the SWHID is `swh:1:rev:b8fe7506c23641ff7bc43deed4573feaa6d03947`.

**Comment by rougier** [comment]
@bpbond Here is a sandboxed version of your article: https://sandbox.zenodo.org/record/748080. Please tell me if everything looks right.

**Comment by bpbond** [comment]
@rougier Looks great to me! Thanks for your help.

**Comment by rougier** [comment]
It's online ! See https://rescience.github.io/bibliography/Bond-Lamberty_2021.html

**Comment by bpbond** [comment]
Hurray! Thank you @rougier and all—an interesting and unusual effort. Cheers!
