### ISSUE TITLE
[Re] Modeling Insect Phenology Using Ordinal Regression and Continuation Ratio Models

### ISSUE THREAD

**Issue by pboesu** [ReScience/submissions#46]
**Original articles:**    
- B. Dennis, W.P. Kemp,and R.C. Beckwith (1986): "Stochastic Model of Insect Phenology: Estimation and Testing." Environmental Entomology 15(3):540–546. https://doi.org/10.1093/ee/15.3.540
- S.G. Candy (1991): "Modeling Insect Phenology Using Ordinal Regression and Continuation Ratio Models." Environmental Entomology 20(1):190–195. https://doi.org/10.1093/ee/20.1.190

**PDF URL:** https://github.com/pboesu/replication_candy_1991/blob/master/article/article.pdf
**Metadata URL:** https://github.com/pboesu/replication_candy_1991/blob/master/article/metadata.yaml
**Code URL:** https://github.com/pboesu/replication_candy_1991

**Scientific domain:** Ecology
**Programming language:** R
**Suggested editor:** @karthik @tpoisot 

### Editor (@tpoisot) checklist

- Reviewer 1
    - [x] assigned @juniperlsimonis 
    - [x] returned
- Reviewer 2
    - [x] assigned @aammd
    - [x] returned

**Comment by rougier** [comment]
@pboesu Thanks for your submission, we'll assign an editor soon.
@karthik or @tpoisot Could you edit this submission (ecology + R)?

**Comment by karthik** [comment]
Unfortunately unable to edit anything at the moment. My apologies.

**Comment by rougier** [comment]
@karthik No problem @tpoisot, can you edit this submission (ecology + R) ?

**Comment by pboesu** [comment]
@rougier Just to declare, that I am still interested in having this submission peer-reviewed. I do appreciate the difficulties of securing editor and reviewer availability in the current conditions (and am guilty myself of delaying a ReScience submission last year), but it would be great if this manuscript could be progressed in the not too distant future.

**Comment by rougier** [comment]
Ouups, I'm deeply sorry for this very long delay, for some reason it went out of my radar. We'll try to accelerate things.

@karthik or @tpoisot Do you have time to edit this submission "Insect Phenology Using Ordinal Regression and Continuation Ratio Models / Ecology / R"

**Comment by karthik** [comment]
Not at the moment. Tim?

**Comment by rougier** [comment]
@FlukeAndFeather @juniperlsimonis @trashbirdecology @ha0ye @jsta @opetchey @karthik @dmcglinn
Dear all, can any of you review this submission in ecology / R for ReScience C (Modeling Insect Phenology Using Ordinal Regression and Continuation Ratio Models)?

**Comment by tpoisot** [comment]
I haven't used R in just about forever, so I'm not sure I'm the best person to do this. Maybe @aammd ?

**Comment by rougier** [comment]
@tpoisot It's only for editing, not reviewing.

**Comment by trashbirdecology** [comment]
what's the desired timeline? i am overwhelmed until mid to late April

**Comment by tpoisot** [comment]
@rougier ok will do then

**Comment by tpoisot** [comment]
@pboesu sorry about the delay, we'll try to make the process as fast as possible

@trashbirdecology do you confirm that you can review it?

@aammd do you have time to look this over as well?

**Comment by FlukeAndFeather** [comment]
I'm keen to review. How quick do you need it turned around? I can set time aside next week.

**Comment by rougier** [comment]
@tpoisot Thanks. I've take freedom to invite reviewers from the board. For publication, just tell me if you need assistance.

**Comment by juniperlsimonis** [comment]
ive got some time next week to review if its still needed, just lmk

**Comment by tpoisot** [comment]
@adbpatagonia and @guysutton have both expressed interest - either one of you, and then @FlukeAndFeather ?

**Comment by tpoisot** [comment]
> ive got some time next week to review if its still needed, just lmk

sweet lord @juniperlsimonis when do you sleep?

**Comment by trashbirdecology** [comment]
if @juniperlsimonis can review soon that's probably for the best, otherwise my turnaround will be real slow.

**Comment by juniperlsimonis** [comment]
> 
> 
> > ive got some time next week to review if its still needed, just lmk
> 
> sweet lord @juniperlsimonis when do you sleep?

what is sleep?

**Comment by aammd** [comment]
hello everyone! not sure if this is still needed but yes, I'd be excited to help :sweat_smile:

**Comment by pboesu** [comment]
Wahay! 🎉 Thanks @rougier and @tpoisot for getting this moving again and to everyone else for their enthusiasm!

**Comment by tpoisot** [comment]
OK so let's do @juniperlsimonis and @aammd - @rougier can you remind me of where the review template is located? It's been a while since I handled a ms.

**Comment by FlukeAndFeather** [comment]
I take it I'm not needed on this review then? Just making sure. Please let me know if you need a backup or anything. Thanks!

**Comment by tpoisot** [comment]
@FlukeAndFeather I think we're good, but @juniperlsimonis and @aammd can tag you if they need backup?

**Comment by rougier** [comment]
@tpoisot @juniperlsimonis @aammd The review instruction are available at https://rescience.github.io/edit/.
Don't hesitate to poke me if needed.

**Comment by aammd** [comment]
hello @rougier @tpoisot et al! What is the deadline for one of these reviews? A quick skim of the Reviewer guidelines didn't reveal anything there about the period of time normally required :) Thank you!

**Comment by rougier** [comment]
It's quite variable but since we're already quite late on this one (my fault), the sooner the better of course...

**Comment by pboesu** [comment]
@aammd From my perspective - I have enough other projects on the go to keep me busy in general :wink: - certainly in April, but it would be nice to get this through before the summer conference season (mid-June) as I am planning to present and eventually submit work building on this manuscript. (At the same time I appreciate these are difficult times - thanks for being a reviewer in the first place!).

**Comment by rougier** [comment]
@tpoisot @aammd @juniperlsimonis @pboesu Let's target April 26 if everyone agrees.

**Comment by juniperlsimonis** [comment]
hopefully still on target for the 26th

**Comment by juniperlsimonis** [comment]
@rougier @tpoisot sorry for the n00b question, but this is my first review, how exactly do I submit the review? here or in the code repo? and as a PR or something else? thanks!

**Comment by tpoisot** [comment]
Good question @juniperlsimonis - a comment here is fine, or you can open issues on the original repo by the author and summarize your comments here. Whatever is actionable for the authors and not too large an investment of your time is something we appreciate and can work with!

**Comment by aammd** [comment]
linked above is my review for @pboesu 's replication! To briefly summarize: I think this is excellent. Not only have you reproduced everything in the original but you've improved them in almost every aspect. The data are better organized. The math is more clearly explained. The code is modernized and well commented. The figures are identical except for some helpful colour.

Code is very clear and well-commented. I got all the errors described in the README, plus one more which had to do with parameter values tried by `optim`. I don't have much to suggest regarding the code: perhaps changing hand-coded Logistic CDFs for `stats::plogis()`. 

in the text, I made one clarifying suggestion around line 65: highlight that the equation is the CDF of a latent logistic distribution, which has a mean and variance of etc. 
I also suggest that in table 1 and 2, the Method column should go on the left of the table. 

That's it! Thank you for the invitation, this was a pleasure.

**Comment by pboesu** [comment]
> @rougier @tpoisot sorry for the n00b question, but this is my first review, how exactly do I submit the review? here or in the code repo? and as a PR or something else? thanks!

@juniperlsimonis Any of those options work for me - so whatever is easiest on your end!

**Comment by juniperlsimonis** [comment]
-- I'm done adding specific issues to the code repo, @pboesu! Nice job with this! --

I really like this paper and applaud you for the work on it! 

I did hit some hiccups in installing and running stuff on my end, and I have some suggestions for a few ways to increase the reliability of the reproduction into the future.

- [Installation issues and improvement suggestions](https://github.com/pboesu/replication_candy_1991/issues/2) 

On the stats implementation side of things, there are a few spots that I think need just a little more work, as I was able to get sufficient fits where your code failed in one spot, for example.

- [VGAM Script](https://github.com/pboesu/replication_candy_1991/issues/4)
- [Optim Sensitivity](https://github.com/pboesu/replication_candy_1991/issues/6)

I have some structure and formatting feedback that, while not critical, will improve the usability for folks in the future.

- [Code structuring and formatting suggestions](https://github.com/pboesu/replication_candy_1991/issues/3)

And then some notes on the manuscript

- [Presenting Computational Robustness of Statistical Fits](https://github.com/pboesu/replication_candy_1991/issues/5)
- [Figures](https://github.com/pboesu/replication_candy_1991/issues/7)
- [Manuscript Text](https://github.com/pboesu/replication_candy_1991/issues/8)

Again, I think this is some really great work you've done here, I just think a little bit more time spent now will make your efforts much more impactful.

This is my first review for ReScience and I really enjoyed this.

Thanks!

-Juniper Simonis (they/them/theirs)

**Comment by pboesu** [comment]
Thank you both for the constructive reviews @aammd @juniperlsimonis ! I'll try to do the revisions in the coming week.

**Comment by rougier** [comment]
@aammd Woudl you mind posting your review in this thread? Once published, we link the paper to the review and if for some reason the repository where you posted your review become unavailable, your review will be lost. Here (ReScience/submission) we can guarantee future access (somehow).

**Comment by rougier** [comment]
@aammd Can you post your review in this thread ?
@pboesu Just tell us when your revision's ready

**Comment by pboesu** [comment]
@rougier I'm just in the process of pulling the revisions together and responding to the reviewer comments. There should be a revised submission in place later today or tomorrow.

**Comment by tpoisot** [comment]
@pboesu perfect - looking forward to the replies.

**Comment by pboesu** [comment]
Ok! Revisions are done! - Thanks again to @aammd and @juniperlsimonis for their constructive comments which encouraged me to dive into the optimisation code much deeper and learn a thing or two along the way!

The overall diff can be seen here: https://github.com/pboesu/replication_candy_1991/compare/v0.1...v0.2

I apologize that the git history is a bit convoluted. Halfway through my revisions, I discovered that my failure to use parameter scaling in the optimisation procedure had created some of the numerical issues I discussed in the original submission and which were commented on by the reviewers. 
Adding parameter scaling resolved several of these numerical instabilities, so there is a set of responses in the git history which were ultimately superceded, but for the sake of completeness I haven't squashed those commits.

I have provided summaries of changes in each of the issues in the replication repository. And a high-level response to each issue is given below

1. [Review by aammd](https://github.com/pboesu/replication_candy_1991/issues/1)
I addressed all but one issues raised by @aammd. This included adding box constraints to one set of optimisations to avoid error messages during the optimisation run, investigating the sensitivity of parameter estimates to using a literal implementation of the inverse logit link versus the corresponding `plogis` function, and some textual/typesetting issues. I did not have a good idea about making the reformatted data set more discoverable than it will be following the publication and archival of the replication paper. As it is, the data are provided in clear text in the original publication (albeit in an 'untidy' format), and I do not think that a separate re-publication of the data beyond the replication paper is justified given the small size of the data set.

2. [Installation issues](https://github.com/pboesu/replication_candy_1991/issues/2)
I responded to these suggestions by providing more explicit information to the user about using or not using `renv` for dependenccy management, both in [README](https://github.com/pboesu/replication_candy_1991/compare/v0.1..v0.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and in [.Rprofile](https://github.com/pboesu/replication_candy_1991/compare/v0.1..v0.2#diff-bd3c4db940418433876cd2f7ba7ab9a320166be4a13a1a29bd169d3a33d4e5ec). Dependency management in R is a mess to be perfectly honest, but for all of it's imperfections and peculiarities `renv` does provide a standardized way to simplify it, even if that comes at the cost of a non-standard file structure (i.e. the repository-specific .Rprofile which is separate from other dependency / function loading code in the project). I hope the added comments and `sessionInfo()` details give the advanced R user sufficient information to make an informed choice in how to approach recreating the runtime environment.

3. [Code structuring](https://github.com/pboesu/replication_candy_1991/issues/3)
Again, I chose a compromise here. I split out function definitions from function use, but otherwise left the structure of the analysis code as is - as sequentially numbered R scripts, that can be run stand-alone if desired. I clarified the role of using binary `.rds` files as intermediate storage, and minimized the messages that are spit out to the console when running the code. I now explicitly encourage the user to step through the scripts to follow the reproduction, although simply sourcing them in order will still reproduce the manuscript without any need for user interaction.

4. [VGAM errors](https://github.com/pboesu/replication_candy_1991/issues/4)
This is the only major issue that I could not resolve. Model fits with VGAM for cloglog link models continue to either error out, or result in false convergence. I have been in communication with the maintainer of the VGAM package, Thomas Yee, and we established that the underlying cause for this is that the models are estimating parameters at the boundary of the parameter space (i.e. cut-point parameters that are very close to 1 on the probability scale).  For the cumulative family Thomas managed to find an initial fix which removes the originally reported error, but the model continues to converge at local optima far from the solution found with the other algorithms. Thomas is keen to further investigate this issue but is unlikely to do so in the near future due to other commitments.  I have commented out all code using `VGAM::vglm` for cloglog link to avoid throwing error messages when running the replication and added language to the manuscript to highlight that this remains an open issue.

5. [Warnings related to probabilities close to 1](https://github.com/pboesu/replication_candy_1991/issues/5)
I have added more details about the data to the manuscript and a description of how the nature of the data (many 0 cell counts) lead to extreme parameter estimates and hence the warnings produced by `stats::glm` when fitting the corresponding models.

6. [Optim sensitivity](https://github.com/pboesu/replication_candy_1991/issues/6)
I have added an appendix which investigates the behaviour of the direct likelihood optimisation under random initial value proposals. This led me to discover that many of the original instabilities (i.e. parameter variation on the order of 1-2% for different initial values) were a result of not appropriately specifying parameter scaling values in `optim`.  I decided to retain the appendix regardless, as I believe it still has some useful results showing that the cloglog link model is intrinsically less numerically stable than the logit link one.

7. [Figures](https://github.com/pboesu/replication_candy_1991/issues/7)
All suggestions in this issue were adressed.

8. [Manuscript text](https://github.com/pboesu/replication_candy_1991/issues/8)
I added details about function arguments and specific algorithms for the fitting functions and qunatified differences in parameter estimates where relevant.

**Comment by aammd** [comment]
@rougier requested I post my review a second time here (if I understood correctly) so I'm doing that now!  😄  once again, great work @pboesu 

-----

This is for your submission to Rescience, issue ReScience/submissions#46

I really like this work! I have read through your article twice, run all the code, and quickly read both replicated papers. I also have some slight experience with ordinal models; I've fit one using brms. Also I am very enthusiastic about insects 🐛 🦋 !


In brief, I think this is excellent. Not only have you reproduced everything in the original but you've improved them in almost every aspect. The data are better organized. The math is more clearly explained. The code is modernized and well commented. The figures are identical except for some helpful colour. 

There are precious few comments or improvements to offer but here are some that occurred to me:

### The code
* `renv` worked flawlessly in my case. 
* I like the numbered scripts, organized with `source`
* great and readable comments
* I am asked to ascertain that "The clarity of the code and instructions must also be judged in the light of the conventions of the field". I think your code and instructions are exemplary and would happily teach from it. (Style-wise, I personally mix base and tidyverse in nearly the same fashion! so according to my personal conventions this is quite correct)

minor points? 

I got all the errors which you forwarn in your README, with one extra. When I ran `code/03_fit_dennis_et_al_model.R` I got 
`1: In sqrt(BB * ddeg[i]) : NaNs produced`

clearly `optim` is feeding in some negative values for `BB`. I wonder if it would work to stick in into a log link, i.e. 
`sqrt(exp(BB_log) * ddeg[i]`
perhaps? or to constrain the values of BB somehow? 

similarly, I notice that you program the CDF of the logistic manually, but you could have used `stats::plogis` to do the same. My guess is that the latter is more numerically stable. So for example

```r
A2 = 230
BB= 3
ddeg = 58
1 / (1+exp(-(A2-ddeg)/sqrt(BB*ddeg)))
```

would be the same as:

```r
stats::plogis(A2, location = ddeg, scale = sqrt(BB*ddeg))
```

I doubt that would actually change anything, of course! ~though it would probably get rid of the error just above.~ It probably won't help with the error just above, if it is indeed caused by `optim`'s choice of parameters and not the cdf function itself.

### The text

Really clear and readable. I was breifly confused around line 65 because the text says "this distribution" , meaning the latent logistic distribution, but equation 4 shows the CDF of this distribution, not the PDF.  You might tweak L65 to something like "The CDF in equation (4) corresponds to a logistic distribution with a mean of.." or something.

### misc questions

* You've made an historical dataset much more accessible and useful by reorganizing and documenting it. Is there a way to make the data itself more available beyond this paper?

**Comment by rougier** [comment]
@aammd Thanks.

**Comment by tpoisot** [comment]
I am going to assume that the :tada: and :rocket: emojis on [the response[(https://github.com/ReScience/submissions/issues/46#issuecomment-850565625) means that @aammd and @juniperlsimonis are happy with the revision, and so this is an **accept** for me.

@rougier - I might need a refresher with the publishing pipeline

**Comment by juniperlsimonis** [comment]
yup! Good faith solid effort to address the concerns I raised. Nice job @pboesu !

**Comment by rougier** [comment]
@tpoisot I can publish it for you, might be easier.  @pboesu I'll try to do it this Friday, don't hesitate to remind me here.

**Comment by pboesu** [comment]
@rougier I have just added the metadata for the reviewers and editor and minted a doi for the [code archive](https://doi.org/10.5281/zenodo.4943258) . Let me know if you need me to do anything else.

**Comment by rougier** [comment]
Acutally we'e now using software heritage for the code. If you go here: https://www.softwareheritage.org/save-and-reference-research-software/ It's quite straightforward to get the SWID.

**Comment by pboesu** [comment]
OK, I've removed the Zenodo DOI and filled in the swh field in metadata.yaml instead. The snapshot on software heritage is here: https://archive.softwareheritage.org/swh:1:dir:fa45767e4bb56f7807fe2081cfe069881f8b049e

**Comment by rougier** [comment]
Thanks. The sandboxed version is at https://sandbox.zenodo.org/record/865592. Can you check everything's ok?

**Comment by pboesu** [comment]
@rougier Yep. That looks great!

**Comment by rougier** [comment]
It's online at https://zenodo.org/record/5006005 and will soon appear on ReScience website.

**Comment by pboesu** [comment]
Excellent! Thanks all!
