### ISSUE TITLE
POST-PROMD: an open-source POST-PROcessing software for Molecular Dynamics simulations

### ISSUE THREAD

**Issue by ghost** [ReScience/submissions#82]
Original article: POST-PROMD: an open-source POST-PROcessing software for Molecular Dynamics simulations

PDF URL: https://github.com/shekaari-theory/POSTPROMD/blob/main/article.pdf

Code URL: https://github.com/shekaari-theory/POSTPROMD/blob/main/post-promd-v.1.0.0.tar.gz

Scientific domain: Computational Physics

Programming language: Fortran

**Comment by khinsen** [comment]
@shekaari-theory Thank you for your submission! At first sight, this looks neither like a replication nor like a reproduction. Could you please explain why you believe your paper fits into the scope of ReScience C?

**Comment by ghost** [comment]
Dear Konrad Hinsen,
Regarding your email, I have corrected the issues and prepared the
manuscript according to
Rescience C latex template. Sorry for the delay and thank you for your
attention.
---
kind regards,
Ashkan Shekaari <https://rt.academia.edu/AshkanShekaari> [Lab in Lap
<http://dx.doi.org/10.13140/RG.2.2.21493.38880>]

**Comment by khinsen** [comment]
Resubmittes as #83
